### ISSUE TITLE
[EPIC] Removal of Prow CI

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#10076]
**Description**

As we decided to not use prow, we need to resolved given issues:

- [x] Prow jobs migration:
  - [x] https://github.com/kyma-project/test-infra/issues/11711
  - [x] #9490 
  - [x] #9491 
  - [x] #9492 
  - [x] #9493 
  - [x] #9494 
  - [x] #9495 
  - [x] #9496 
  - [x] #9497 
  - [x] #11627
- [x] Removal of Prow:
  - [x] https://github.com/kyma-project/test-infra/issues/9768
  - [x] https://github.com/kyma-project/test-infra/issues/11956
  - [x] https://github.com/kyma-project/test-infra/issues/12090
  - [x] https://github.com/kyma-project/test-infra/issues/11889
  - [x] https://github.com/kyma-project/test-infra/issues/12147
  - [x] https://github.com/kyma-project/test-infra/issues/11628
  - [x] https://github.com/kyma-project/test-infra/issues/12709
  - [x] https://github.com/kyma-project/test-infra/issues/12470
  - [x] https://github.com/kyma-project/test-infra/issues/12770
  - [x] https://github.com/kyma-project/test-infra/issues/13093
  - [x] https://github.com/kyma-project/test-infra/issues/13329
