### ISSUE TITLE
Testing strategy for image-builder

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#11238]
The image-builder application is composed by few components. These components are running in different tools and technology stacks. Application components exposes it's APIs and interact each other. The component and API that is used by component must be compatible. The compatibility must be maintained when any of application component is changed. To maintain compatibility we must test the application changes in a way which will prove components can interact properly.

Image builder components are.
- [ ] Image builder GitHub action.
- [ ] Image builder reusable workflow.
- [ ] Image builder oci-image-builder ADO pipeline.
- [ ] OIDC token verifier.
- [ ] Image signer golang binary.
- [ ] Tags parser golang binary.

We must define a way how to test each component in insolation, when it is changed and how to test compatibility with components it interacts with.

- [ ] We have testing strategy defined for each application component.
- [ ] Testing strategy must describe how to test component in insolation.
- [ ] Testing strategy must describe how to test component compatibility with components it interacts with.
- [ ] Testing strategy is documented.
- [ ] PoC and decide if we want to implement contract tests. If yes, then the contract tests strategy is documented.
- [ ] PoC and decide if we want to implement e2e tests. If yes, then the contract tests strategy is documented.
- [ ] Each component is tested according to defined testing strategy.

**Comment by KacperMalachowski** [comment]
During implementation of kyma/oci-image-builder#67, we learned:

**Comment by Sawthis** [comment]
Migrated to `kyma/oci-image-builder/issues/285`.
