### ISSUE TITLE
Kubernetes upgrade from ver 1.29 to 1.30

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/test-infra#11367]
**Description**
We are going to upgrade Kyma to support K8s version 1.29 after 10.October.2024. This requires an updated of all existing pipelines and preview-jobs to use 1.30. (Please complete this task before end of October.2024)

**Tasks**
- [ ] Prow jobs are based on k8s `1.30` - see [example PR](https://github.com/kyma-project/test-infra/pull/5733/files)
    - [ ] `kyma-upgrade-gardener-kyma2-minor-versions` job should be still using the currently used k8s version and not be updated
    - [ ] Existing release jobs should also not be updated to use the new K8s version
- [ ] Default version for kubectl is `1.30` (Docu, Prow)
- [ ] Configure preview job to verify if Kyma is compatible with k8s`1.30` (**next** k8s version  -  see [example PR](https://github.com/kyma-project/test-infra/pull/5685))
     - [ ] create tickets (and link them) for other teams if the pipeline gets red (ping release-manager and provide him the issue-link)

Previous upgrade: https://github.com/kyma-project/test-infra/issues/10579

**Comment by zhoujing2022** [comment]
This step is not needed any more. Comments from @Sawthis : https://github.com/kyma-project/test-infra/issues/10579#issuecomment-2230054006
