### ISSUE TITLE
[CI/CD] Migrate prowjobs out of Neighbor's Prow - Neighbors

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#11627]
**Description**
The prow jobs owned by the Neighbors team have to be removed and if necessary substituted with something else.
To simplify the process here is a list of the issues that should be migrated by Neighbors team.

- [x] https://github.com/kyma-project/test-infra/issues/12287
- [x] https://github.com/kyma-project/test-infra/issues/9771
- [x] https://github.com/kyma-project/test-infra/issues/9765
- [x] https://github.com/kyma-project/test-infra/issues/9763
- [x] https://github.com/kyma-project/test-infra/issues/9764
- [x] https://github.com/kyma-project/test-infra/issues/9766
- [x] https://github.com/kyma-project/test-infra/issues/9767
- [x] https://github.com/kyma-project/test-infra/issues/11828
- [x] https://github.com/kyma-project/test-infra/issues/9769
- [x] https://github.com/kyma-project/test-infra/issues/11384
- [x] https://github.com/kyma-project/test-infra/issues/9434
- [x] https://github.com/kyma-project/test-infra/issues/9925
- [x] https://github.com/kyma-project/test-infra/issues/9940
- [x] https://github.com/kyma-project/test-infra/issues/10903
- [x] https://github.com/kyma-project/test-infra/issues/12056
- [x] https://github.com/kyma-project/test-infra/issues/12153
- [x] https://github.com/kyma-project/test-infra/issues/12145
