### ISSUE TITLE
Split image-builder in to multiple tools

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#12140]
**Description**

A [image-builder](https://github.com/kyma-project/test-infra/tree/main/cmd/image-builder) tool act as a client and server. Server code support two running modes, signing images or parsing tags. Each scenario supported by the tool is executed alone in separate runs. Because modes are executed independent we should separate code responsible for this tasks and create separate tool for each scenario.

**Reasons**

By separating duties, each tool will be developed independent. They will be released independent. The scope of each change will be smaller.

**Acceptance Criteria**
- [x] https://github.com/kyma-project/test-infra/issues/12845
- [ ] https://github.com/kyma-project/test-infra/issues/12850
- [ ] https://github.com/kyma-project/test-infra/issues/12851
- [ ] https://github.com/kyma-project/test-infra/issues/12852

**Comment by Sawthis** [comment]
Migrated to `kyma/oci-image-builder/issues/281`.
