### ISSUE TITLE
Assure cleanup of vms and gke clusters

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#177]
We need to make sure all the vms and gke clusters we create for kyma integration jobs are properly cleaned up. There could be some cases leading to leftovers. 

We can consider setting TTLs for the instances and creating a periodic cleanup job to delete the instances based on their TTLs.

Tasks:
- [x] create a tool to remove clusters @Tomasz-Smelcerz-SAP => #334
- [x] create a tool to remove VM instances @Tomasz-Smelcerz-SAP => #342
- [x] create a periodic prow job to remove clusters (dryRun=true) @Tomasz-Smelcerz-SAP => #363 
- [x] switch periodic cluster cleanup job to final configuration (dryRun=false) @Tomasz-Smelcerz-SAP  => #373
- [x] create a periodic prow job to remove VM instances (dryRun=true) @Tomasz-Smelcerz-SAP => #375
- [x] switch periodic cluster cleanup job to final configuration (dryRun=false) @Tomasz-Smelcerz-SAP  => #377

**Comment by Tomasz-Smelcerz-SAP** [comment]
I want to create two tools: One to remove clusters, one to remove single VM instances.
Both tools will be configured with
- name pattern - to filter by name
- "ageInHours" threshold - to filter by "age" in hours
- label (optionally) - to filter by label (if API supports it)

Both of these tools can be then run in any desired way: in parallel, one after another, on different schedules etc.

The need for two different tools is:
We have two kinds of VMs:
- Provisioned for the integration-test clusters which are also deleted automatically by GCloud along with the clusters (no need to delete them separately)
- Standalone ones provided for kyma-integration job. These must be removed separately, if orphaned.
