### ISSUE TITLE
Provisioning GKE cluster for integration tests

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#20]
**Description**
Implement installation and test of kyma project with GKE cluster using Prow.

AC:
Deliver artifacts (sources in github) necessary to create/re-create the following pipeline:

- [x] activation of the process on pull request comment (1) -> @kfurgol #71
- [x] checkout sources (2a) -> @strekm 
- [x] add "pipeline" script that integrates all steps. Hardcode values that are not available yet -> @Tomasz-Smelcerz-SAP  -> PR #100
- [x] build Kyma-Installer image (charts included #866 ) (2b, docker-in-docker?) -> @Tomasz-Smelcerz-SAP -> #122
- [x] push Kyma-Installer image to gcr (pulls folder?) (2c) -> @Tomasz-Smelcerz-SAP -> #122
- [x] reserve IP address (4a) -> @kfurgol #94
- [x] generate domain name like pullxx-random-name.kyma.pro (4b) -> @kfurgol #92
- [x] create DNS A record for IP and domain (4c) -> @kfurgol #92
- [x] generate self signed certificate for the domain (5) -> @kfurgol #97
- [x] provision GKE cluster (6) -> @strekm, [PR-1452](https://github.com/kyma-project/kyma/pull/1452)
- [x] provision and deprovision all external resources (IP, DNS, Cluster) -> @Tomasz-Smelcerz-SAP (https://github.com/kyma-project/test-infra/pull/109)
- [x] install tiller (7a) -> @jakkab -> PR #121 
- [x] apply kyma-installer deploymenmt (with proper IP and domain) (7b) -> @jakkab -> PR #121
- [x] trigger installation (action=installl) (7c) -> @jakkab -> PR #121
- [x] release IP address and delete DNS record -> @kfurgol #106 #107
Stretch:  Pipelines steps can be triggered independently (if easy enough to implement)

After provisioning trigger those actions (outside of scope of this task):
- run tests 
- [x] deprovision cluster (and IP address) -> @strekm working on deprovision cluster, [PR-1452](https://github.com/kyma-project/kyma/pull/1452)
- set github check state for pull request

Consider implementation as orchestration of small jobs doing one thing at once (e.g. set up DNS, provision cluster, generate TLS) - avoid implementation with one big script.

**Reasons**
This task is a preparation to move CI from minikube in docker to real cluster on GCE. Prow is the kyma community choice for CI/CD. 
Minikube in docker has serious limitations (kubeadm is not supported), therefore other way of testing kyma is required.

**Comment by pbochynski** [comment]
Set up cluster on GKE flow:
- reserve IP address 
- generate domain name like pullxx-random-name.kyma.pro
- create DNS A record for IP and domain
- generate self signed certificate for the domain
- provision GKE cluster
- install tiller
- apply kyma-installer deploymenmt (with proper IP and domain)
- trigger installation (action=installl)

**Comment by Tomasz-Smelcerz-SAP** [comment]
script that creates a dns entry (record type "A") for given IP address:

AC:
- script accepts IP address as an input
- script generates domain name like: pullXYZ-random-name.kyma.pro (I'd say about 12 random chars should be enough to avoid collisions)
- script adds "A" record in kyma.pro zone
- script verifies the DNS entry works as expected (by resolving host name and verifying it matches IP given as input).
- script waits up to five minutes for correct DNS propagation, then gives up.
- See example: ts-remove-me.kyma.pro

**Comment by PK85** [comment]
Please use kubernetes version same as minikube which is 1.10. Maybe we should even add that to the installation guide.

**Comment by jakkab** [comment]
Running tests implemented in #139
