### ISSUE TITLE
Automated rebuild dependent images and no-bump solution for prowjobs.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2633]
**Description**

Our Prow should be able to pick links between images and rebuild dependent images without human intervention. It should be additional mechanism available for every willing user.

Every makefile can define _metadata_ target which when called will print paths too makefile of parent images. If new parent image version was pushed we can trigger pubsub messages with image name which will trigger periodic job. This job will call all images makefiles _metadata_ target and rebuild all image which depend on changed image.

Makefiles can also contain steps for tagging and pushing image with _current_ tag. This tag should be added on presubmit builds. Builds would be executed with build arg which contain master branch commit on which image was build. Value of build are will be set as value for IMAGE_COMMIT label and environment variable. Environment variable will be printed to logs by entrypoint. This will give us possibility to identify exact commit for images and containers. The _current_ tag can be then used in prowjobs definitions along with _imagePullPolicy: Always_ to use newest image build on master branch without need to bump tags in prowjobs.

- [x] Automated trigger of test on PR raised by dependabot. #4625
- [ ] Merging update PRs without human review. #4786
- [ ] Deploy new versions of artefacts to the running systems.

**Reasons**

We need automation for building images and using newest versions in prowjobs. This will decrease workload on all teams as well decrease number of old images used in prow.

**Comment by dekiel** [comment]
To simplify solution for developers, we can drop idea of having metadata target in makefiles and just scan all Dockerfiles to match values FROM directives with name of rebuild image.
To avoid need to update FROM image tag in Dockerfiles we should use dynamic generated Dockerfile with variable as an image tag. This will solve problem of approving and merging tag changes in github.
The name of label IMAGE_COMMIT should be changed to io.kyma-project.test-infra.commit

**Comment by dekiel** [comment]
At present autobumper i keeping our yaml files updated with latest available OCI images versions.
Introducing dependabot configuration for updating Dockerfiles with latest versions should give us automated updates on daily basis. This will be introduced in #4582 
Same dependabot will maintain our go module versions up to date. Thanks to rebuilding all tools and OCI images with newest modules versions, updates are propagated to used artefacts.

We should consider following remaining related topics.
- Upgrade automated rebuild of components to react immediately to the changes introduced in components definition. Update chain should be executed without delay of one day, so feedback is available right after the change and possible troubleshooting will be easier.
- Last step of update chain should propagate new versions of artefacts to the running systems.

**Comment by dekiel** [comment]
Automerge bot and dependabot are updating Dockerfiles and prowjobs with newest image versions.
