### ISSUE TITLE
Increase release process automation level.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#4799]
**Description**

We did multiple releases after recent changes in release process. These changes decreased number of manual steps. There was no major issues with release process and tools. Because of that we consider changes are reliable. Our documentation about release process got updated to reflect these changes as well.  After release of Kyma 2.0 we should revisit our release process and tools in order to recheck if we can increase automation level or make a process simpler. 

**Reasons**

Last time we did improved release process, some steps were not considered for automation at all. Last changes mainly focused on commit and branching strategy as well automation of triggering release and publishing tag.

**Acceptance criteria**

The process should not contain any manual steps like creating branches, bumping versions in files etc.
All parameters needed to run a release process should be provided through github PR.
We should not use two different CI/CD systems like prow and github actions. Only one should be used. We prefer to use Prow.

**Comment by Ressetkk** [comment]
Some steps we should take in consideration:
* [ ] create tooling that would allow easily operate over releases for release masters, that eventually would be handed over to the release team.
* [ ] effectively remove kyma-artifacts jobs and promote the artifacts only when the release is made. Kyma can be installed using local sources. That effectively removes the need of this prowjob.
* [ ] use less prowjobs - not define them per branch, as it's horrible to maintain. This should be considered after figuring out #4818 
* [ ] Completely remove GitHub action manual workflow in favour of the tooling mentioned above.

**Comment by dekiel** [comment]
We decide to not invest in improvements of current Kyma release process.
