### ISSUE TITLE
Golint is deprecated

### ISSUE THREAD

**Issue by halamix2** [kyma-project/test-infra#4943]
**Description**

Golint was deprecated: https://github.com/golang/go/issues/38968
A golint is run by before-commit.sh script. This script is starting multiple tests/linters apart from golint.
A list of features provided by script should be used as a list of prowjobs to create.
Each prowjob should implement one feature from the list.
At the end all features must be provided by some standalone prowjob with dedicated tool.

- [ ] Check if we need to use golint or other tools we have cover all of its use cases. #5746
- [X] check if we can replace golint with https://github.com/mgechev/revive
- [ ] Golangci-lint linter only files changeed in PR. #5745
- [ ] Define configuration for each repository.
- [ ] Define prowjobs for each repostiory.
**Reasons**

- One of the PRs is stuck on the golint tool dependencies: https://github.com/kyma-project/test-infra/pull/4905

**Acceptance Criteria**

- [ ] Replacement can work with files changed in PR only.
- [ ] Replacement can work against whole repository.
- [ ] Prowjob running a linter should not have dependency to test-infra.
- [ ] Replacement should allow for different configuration per repository.
- [ ] Prowjobs running a replacment should be stored in test-infra repository.
- [ ] Replacement must cover all features already provided by before-commit.sh script.

**Attachments**

/kind deprecation

**Comment by Ressetkk** [comment]
Let's try to deprecate the entire [`before-commit.sh`](https://github.com/kyma-project/test-infra/blob/main/development/tools/before-commit.sh) script. We can use presubmits that will run on every PR that touches go code.

**Comment by Ressetkk** [comment]
Maybe it'd be good to introduce the separate job that runs listing against entire codebase with using https://github.com/golangci/golangci-int.

**Comment by Ressetkk** [comment]
Static check are all over the place. We use at least 3 different binaries for static checks and different approaches.
* We have before-commit.sh that directly runs linter across go codebase as a step
* We have a makefile check that does the same
* There is also https://github.com/kyma-project/kyma/tree/main/hack directory maintained only by @clebs which contains the static checks shell script

We really need to look at some unified approach for static checks for all go code. Let's validate if golangci-lint running as a separate job would be enough. That job would run only when the go code is replaced. We can maintain it and configure autobumper so bumping is easy.

Let's work on that ASAP since it's getting out of hand.

**Comment by Ressetkk** [comment]
No need to reopen this. https://github.com/kyma-project/test-infra/issues/4943#issuecomment-1088940322 already contains solution to this issue.

**Comment by Ressetkk** [comment]
I believe we already agreed to use `golangci-lint` for all go-related codebase static checks. No need to keep this issue for this long.
/close
