### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5112]
**Description**

This is our team goal. We would like to put more structure and rules in to documentation for tools offered by Neighbors. We aim to have common approach where we store our documentation and how we make it easily accessible for a users. We will work on finding or building some tool which will support us in keeping an order in our documentation. First we would like to make our docs easier to find and use. We believe this will have positive impact on time all spent on consultancy.

**Reasons**

Our documentation is highly distributed over test-infra repository, what sometimes make hard to learn about tools we have.
This high level of distribution has no defined structure, thus it might be a source of documentation degradation.

**Acceptance Criteria**

- [x] setup a tool automatically maintaining documentation index page https://github.com/kyma-project/test-infra/issues/6113
- [x] design documentation structure https://github.com/kyma-project/test-infra/issues/6147
- [x] define internal team rules related to documentation. - Kyma wide rules, neighbours DOD and documentation structure is enough for us.
- [x] identify missing or outdated documentation for offered tools #6144
- [x] extend onboaridng guides for kyma devs https://github.com/kyma-project/test-infra/issues/6177

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/blob/main/docs/prow/prow-jobs-quick-start.md

**Comment by dekiel** [comment]
We remove an acceptance criteria "create an index with documentation inventory" as we consider it as the same as second one "setup a tool automatically maintaining documentation ...".
@dekiel  will create a separate issue for "identify missing or outdated documentation for offered tools" to get a list of documentation to remove.
@dekiel will setup a separate issue and meeting for making an agreement about "design documentation structure". Outcome of it should be and written set rules/best practice.
