### ISSUE TITLE
[CI] Enable in repo config.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5177]
**Description**

Enable in repo config support in Prow. Kyma modularisation main assumption is that particular components will be developed in separate independent repositories. Teams responsible for the component will work within component repository. It will be convenient for the teams to keep their prowjobs definitions within their repositories instead in test-infra. Additionally we would like to decrease level of involvement in maintaining teams prowjobs. We would like to stop review code change for every prowjob existing on Prow. Having prowjob definitions in components repositories will be more natural. A test-infra repo can still contain prowjob definitions for anything related to infrastructure maintenance, releases, automations. 

Rendertemplate must be able to render prowjob definitions as inrepo config by loading templates and config from test-infra repo. This way we will keep consistent structure of prowjobs definitions and single source for global configsets for all repositories with inrepo config.
Pjtester must support testing prowjobs defined as inrepo config.
Security requirements must support inrepo config scenarios.

**Tasks**
- [x] Rendertemplate generate inrepo config prowjobs with template from test-infra.
- [x] Rendertemplate generate inrepo config prowjobs with global config sets from test-infra config.yaml file.
- [x] Pjtester can run test for prowjob from inrepo config. #5766
- [x] Autobumper can update image tags in inrepo config prowjobs.
- [ ] Rendertemplate support inrepo prowjobs definition syntax. #5764
- [ ] Validation inrepo prowjob definitions against data files #5765
- [x] #6587
- [ ] Automatically update prowjobs defined for all repositories when repository state change. #6339 
- [ ] Documentation update.

**Acceptance Criteria**

Rendertemplate support inrepo config and developers can use templates and configSets defined centrally in test-infra repository.
Pjtester support testing prowjobs defined as inrepo config.
Prowjobs defined as inrepo config have syntax checks
Prowjobs defined as inrepo config have check against requirements to run on trusted cluster.

**Comment by Halamix2** [comment]
Autobumper can update image tags in inrepo config prowjobs out of the box: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/generic-autobumper/README.md

**Comment by Ressetkk** [comment]
So what do we do with this issue? Lookin at the AC I can see that the most significant part is done. I would say it's easy to wrap this up if we drop the missing criteria?
* Developers don't like rendertemplates so if we could drop the need to use it for them some Acs will be invalidated
* We restrict usage for pre/postsubmits only for single cluster - already done and present in prow config https://github.com/kyma-project/test-infra/blob/f4dcd6b9e7af74ca4c9ce8091d2adf2cf4760829/prow/config.yaml#L228C1-L228C1
* For the documentation - there are 2 official sources https://docs.prow.k8s.io/docs/inrepoconfig/ https://docs.prow.k8s.io/docs/jobs/
* for now we can have basic simple validation provided by official prow's checkconfig utility - we already have the jobs based on official docs in https://github.com/kyma-project/test-infra/blob/main/prow/jobs/test-infra/checkconfig.yaml and they already have annotation validation for owner and description

We are basically ready to roll it out to make maintenance of current things much simpler. Even for us when we decide to have more repos than one...

**Comment by tobiscr** [comment]
Descoped as we are not investing further into Prow. Closing it.
