### ISSUE TITLE
Define jobs for test-infra repository

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#54]
- [x] check/validate config.yaml and plugins.yaml on PR #119
- [x] create jobs for publishing buildpacks: #116
- [x] create jobs for validating component yaml definitions: #133 
- [x] Optional: run shell checks #126

**Comment by crabtree** [comment]
Additionally we should verify if cluster files (config.yaml, plugins.yaml) are consistent with config.yaml.tpl and plugins.yaml.tpl.
