### ISSUE TITLE
Migrate Pipelines to Gardener Live environment

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5435]
Reoccurring issues with infrastructure availability on Canary instance causes Prow Pipelines to fail therefore  we are seeking for environment that will provide high availability of Gardener Services and Cluster API server. We will migrate Prow Pipelines from Gardener Canary to Live instance.

### Tasks:
- [x] create [CAM request](https://bc.spc.ondemand.com/sap/bc/webdynpro/a1sspc/cam_wd_central?item=request&profile=Gardener%20LIVE%20CREATE%20PROJECTS#)
- [x] Changing secrets (kyma-prow-gardener kubeconfig) to the Prod environment is the fastest way of pointing all pipelines to the new environment
- [x] Set cluster quota: 50
- [x] Cleanup Gardener Canary

**Comment by kasiakepka** [comment]
Still waiting for approval.

**Comment by kasiakepka** [comment]
kyma-prow project on Canary is deleted.
