### ISSUE TITLE
Implement protected tags

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5455]
## Reasons
Currently anyone with write access to a repo can push any tags and create release. There’s no auditing/logging of tag changes.
Setting up protected tags sounds like an easy way to mitigate this problem.
https://github.com/kyma-project/test-infra/issues/5492

### Task
Set protection rules on repositories: kyma, cli

AC:
- [ ] Make sure that all people responsible have necessary privileges to perform the release on both repositories (kyma and cli)
- [ ] Protect all tags on kyma and all tags except for `stable` on cli repository
- [x] Test the solution on Github test project. See https://github.com/kyma-test-infra-dev/test-infra/actions

**Comment by kasiakepka** [comment]
Releases are created by `github-actions` user,  it can have only `write` access. Creating tags that match a tag protection rule requires admin or maintainer role. Write access is probably not sufficient. According to the documentation `GitHub Apps require the Repository administration: write permission to modify a protected tag.` however it is something different than creating protected tag.

**Comment by kasiakepka** [comment]
We have to run Github actions using custom user (like KymaBot). @Ressetkk , can you please take over and create necessary secrets?

**Comment by dekiel** [comment]
We made a decision to not invest more in old release process. At present we don't see need to use tags in modular Kyma.
