### ISSUE TITLE
Create tool that run docker builds on Google Cloud Build

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5637]
With the results of https://github.com/kyma-project/test-infra/issues/4935 we agreed that we need to have a tool that is able to run Docker builds on Google Cloud Build.

The way the tool can work is to act as a wrapper around command `gcloud builds submit` and underlying `cloudbuild.yaml` file.
For each file a set of [substitutions](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values) which the tool would automatically, or with given flags, fill them during the execution. Then the log would be available in the build-log.

~~🟥 Evaluate if https://github.com/kubernetes/test-infra/tree/master/images/builder meets all the requirements above.~~
This tool is not able to meet some of the requirements above:
❌ It cannot build multiple images at once (multiple build dirs)
❌ It doesn't allow to define custom format for tags
❌ Doesn't allow to push images to multiple registries
❌ Doesn't have the ability to hook in the build process

**Tasks**

- [ ] Prepare infrastructure and implement gcbuild for test-infra repository #5835
- [ ] Evaluate Makefile steps regarding build infra #5834
- [ ] create gcbuild tool #5726
- [ ] Prepare infrastructure and implement gcbuild for kyma-project and kyma-incubator projects. #5891
- [ ] Confirm we are able build equal images locally and on CI. Share test images builds results with @jakobmoellersap 

**Acceptance Criteria**

Tool needs to include the following features:
- [x] Runs from ProwJob.
- [x] Is able to build multiple images in one run.
- [x] Is able to apply multiple tags for image.
- [x] Works without relying on Docker-in-Docker (SLC-29).
- [x] Tag can be assumed automatically, however, there should be a possibility to override it.
- [x] (Optional) Developers should be able to define it's own tags.
- [x] Required tags must be enforced in automated way (without human involvement).
- [x] Required registry URL must be enforced in automated way (without human involvement).
- [x] Required configuration must be provided from one central source.
- [x] It should be possible to provide full runtime configuration via config files or flags.
- [x] Pushing to different registries is possible.
- [x] Because we run on GKE, tool runs on standard credentials provided by GKE.
- [ ] (Optional) Possible build of one image in multiple variants (different versions of binaries in image).
- [x] Production tags have format `vDATE-[HOUR]-shortSHA`, or other semantically versioned  in order to bump them with existing autobump solutions (generic-autobumper, Dependabot).
- [ ] Have ability to hook in the process for image signing, scans and other external integrations (maybe use middleware pattern)

Diagram:
```mermaid
flowchart TB
pr[Open PR with Dockerfile changes]
fail(return error and fail job)
success(Finish job and return success)
subgraph ProwJob
start(Start application)
opts[Gather startup options from flags and run preflight checks]
checks[Run static checks on cloudbuild.yaml file]
isCI{Is application running in CI?}
isPre{Is application running in Presubmit?}
isDevRegistry{Is dev-registry flag set?}
setDevRegistry[Set _REPOSITORY to Development registry in build option]
PRTag[Set tag to `PR-$PR_NUMBER`]
commitSHA{Is COMMIT_SHA env variable present}
gitClient[Fetch commit SHA from git client]
envSHA[Fetch commit from env variable]
buildTag[Build tag from existing information]
setTag[Set tag in build option]
initLogs[Initialize log files]
ifSilent{Do we run in silent mode?}-.Yes.->noStd[set logging only to files]
run[gcloud builds submit with all options set]

ifSuccess{Is GCB succeeded?}
PRTag-->setTag
buildTag-->setTag-->initLogs-->run
setTag-->ifSilent
noStd-->initLogs
isPre-.No.->commitSHA
isCI-.No.->gitClient
commitSHA-.Yes.->envSHA
commitSHA-.No.->gitClient
envSHA-->buildTag
gitClient-->buildTag
start-->opts--Pass-->checks
checks--Pass-->isCI
isCI -.Yes.->isPre
setDevRegistry-->PRTag
isPre-.Yes.->isDevRegistry
isDevRegistry-.Yes.->setDevRegistry
ifSuccess-.Yes.->success
ifSuccess-.No.->fail
end

subgraph GCB
build[Build images]
printLogs[Print logs]
pushImages[Push built images]
build-->printLogs-->pushImages
end

pr-->ProwJob
opts --Fail-->fail
checks--Fail-->fail
run-->GCB
GCB-->ifSuccess
```

**Comment by dekiel** [comment]
I've added few points to the acceptance criteria list and want to give some more context about my understanding of this points.
- Is able to apply multiple tags for image.
A tool should allow to define multiple tags to apply to build image. A tag value can be passed as is or its value will be generated by the tool. Applying multiple tags to the same image must not require multiple builds of the image.
- (Optional) Developers should be able to define it's own tags.
A developers can define their own tags to apply on a build image. They can pass tag value directly or provide logic to generate it at the time of build. A developers tags must not exclude/replace required tags.
- Required tags must be enforced in automated way (without human involvement).
A tool/solution must apply required tags with defined structure and value. This must be enforced by using some automated tests or applying mechanism which is not possible to workaround by developers. This must not relay on code review process and ownership of each and every build configuration file and/or prowjob in all repositories.
- Required registry URL must be enforced in automated way (without human involvement).
Same as enforcing required tags.
- Required configuration must be provided from one central source.
Required configuration such as tags, registry URL or any other needed must be defined in one place. This place is a source of truth for required configuration applied by the tool at build time. Required configuration must be at least defined per repository.
- It should be possible to provide full runtime configuration via config files or flags.
All data needed by the tool to build image should be provided in one consistent way. That means all can be defined in config file or all can be defined as flags. Tool can provide one or both ways, but it must not be required to provide part data as config file and part data as flags. Flags should be used to change a tool working mode/behaviour, like ci or local mode.

 
> Production tags have format vDATE-[HOUR]-shortSHA

Can we use a format `major.minor.patch-prerelease+build_metadata`?
Where:
- major.minor.patch is a version which is currently under development.
- prerelease is an image build time represented in millis.
- build_metadata is a short commit SHA used to build image.
Such format is compatible with semantic versioning 2.0.

**Comment by Ressetkk** [comment]
@dekiel 

1. Every developer can define their own image tags as entry in the `cloudbuild.yaml` file. They will need to add it in the `args` value as part of `docker build` command and in the `images` field to push it to registry. Refer more to the linked PR.
```yaml
images:
  - $_REPOSITORY/tool:$_TAG
  - $_REPOSITORY/tool:latest
  - $_REPOSITORY/tool:i-am-a-teapot
```
2. It's an optional so I won't be dwelling into that topic, as it's partially resolved by point 1. I can provide functionality that allows passing environment variables as substitution, or defining substitutions as flags in the future if it's required.
3. As for now, the tag is hardcoded into format `vDATE-shortSHA`. I have removed the flag that allowed changing the tag template at runtime. The tool also enforces that `cloudbuild.yaml` file includes a $_TAG substitution, so the tool can work properly.
4. Tool also incorporates the enforcement rules for $_REPOSITORY substitution. If the default values is not present in the cloudbuild.yaml, it will fail prematurely. This value is considered as **production** value. Additionally when running on presubmit job we can use flag `--dev-registry`, so the development registry is easily overriden.
5. expl. below.
6. What is a central source? Do you want a program to be configurable by a config file? Right now I can provide entire runtime configuration by flags and modify them as I please. I can load several configuration options from file, like `dev-registry, project, log-dir`, does it really make sense? It will still require flag to load that config from somewhere.

We can add to the Tag structure anything we want. It really depends on what we extract from the git. For now the tag has this format, because it works with current solutions (Dependabot, generic-autobumper)

Please review the code and then let's discuss which AC it meets.

**Comment by dekiel** [comment]
@Ressetkk 
Ad. 3. Is DATE and shortSHA values delivered by the tool?
Ad. 5 and 6. A central source is a one place/source which is used for all executions of the tool. If we provide configuration with flags, then changing a configuration will require placing changes in all prowjobs using the tool. This is what I want to avoid. Lets use a `--dev-registry` as an example. If we are going to provide value for that flag and we would need to change that, we will have to find all prowjobs and change it's definition. If we would keep this in central source, we can change it only there and tool will use a new value. In terms of providing configuration for the execution I want to avoid that some data like variants we provide in files and some data like dev-regostry we provide as flags. As developer I would like to provide all required data as files or as flags not part as files and part as flags.

**Comment by dekiel** [comment]
@Ressetkk There is one thing we missed in the discussion and possibly in a requirements. At present we use a makefiles to define build steps. We have a common makefile which can be taken as is or included in another makefile. Even when taken as is, only part of steps can be executed. With a new tool we can provide a common cloudbuild.yaml file however all steps will be executed. There is no way to decide which steps to execute or include some steps from common cloudbild.yaml file. We need think how much this flexibility we need and how we can eventually provide it.

For now I see two ways of dealing with that.
1. We could create a common steps and use rendertemplate tool and templates to inject them in to cloudbuild.yaml file. This way developers could use only common steps to construct their cloudbuild.yaml or inject some common steps in their cloudbuild.yaml file.
2. We could use a Cloud Build golang client library to construct a Build resource to include only steps defined by developer. I think this way will require to define syntax for input file which will define which steps to use and what is their definition. This approach will require much more effort to develop it and probably to use it.

**Comment by Ressetkk** [comment]
@dekiel I would really go against that. Here's why:

* When I was designing the tool I wanted to deprecate the concept of common makefiles. It gave us pretty hard time in understanding what's going on when something breaks. I personally had to spend a lot of time decoupling the makefiles to fix one simple error and I didn't like it. With the approach as simple as possible there is only one place of failure - an independent file that someone defined
* That would **require** to use gcloud go library and write custom parser. To merge 2 separate cloudbuild files, we'd have to override the file before pushing it to GCB. This is an error-prone configuration, which can be pretty tough to test 
* With current approach we give a lot of flexibility - we provide tooling that ensures minimal requirements that each cloudbuild are met, we give a free possibility to define cloud build steps as devs please, we provide good functionality to run the same pipelines with different variables (variants) concurrently

**Comment by dekiel** [comment]
Roll out of this tool will allow us to remove privileged containers usage in prowjobs. This is a requirement for https://github.tools.sap/kyma/test-infra/issues/63

**Comment by dekiel** [comment]
Let's stick with mounting GCP SA credentials as secrets. Switching to workload identity will be done later.

**Comment by dekiel** [comment]
I've promised @jakobmoellersap to test and confirm we have reproducible builds for local and CI builds. Once we will have some images build on test-infra with gcbuild tool on CI lets sync with Jakob and confirm we meet requirements.

I've added task to the list on this issue.
Jakob comment about building equal images https://github.com/kyma-project/test-infra/issues/5834#issuecomment-1216916769

**Comment by jakobmoellersap** [comment]
I want to throw in here that there are also existing toolings available that we could integrate later on, such as https://slsa.dev/ that take care of build integrity checks. Maybe worth taking a look and evaluating if we just generate build verification data early on.

**Comment by dekiel** [comment]
@Ressetkk do we still need this issue? Do we have some Epic to represent `kaniko-build` implementation?
