### ISSUE TITLE
Automate secrets rotation for Gardener, KMS and GCP service accounts.

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#5691]
**Description**

 
Automate secrets rotation for Gardener, KMS and GCP service accounts.

**Reasons**

Fullfilment of corporate requirements for SLC-29.
Enabled Gardener rotation o keys. https://github.tools.sap/kubernetes-canary/issues-canary/issues/2198
Access to gardener is a main dependency for most of our tests running on Prow. We must have automated keys rotation to not stop development due to no access to gardener.

**Tasks**

- [x] create tool to disable/destroy old KMS key - #5290
- [x] Find usage of all GCP service accounts. #5747
- [x] Create tool to rotate GCP service account keys #5748
- [x] Update GCP service account key used in Gardener. #5749
- [x] Integrate tooling kyma with GCP secret manager. #3960
- [x] create tool to rotate Gardener service account keys - #5725
- [x] Integrate Jenkins with GCP secret manager -  #5832

**Acceptance Criteria**

- [x] All keys must be rotated and updated without human intervention.
- [x] All keys must be updated without long downtime. Max 15 minutes.
- [x] Rotation failures must be alerted on neighbors slack channel.
- [x] Keys must be rotated at least 5 days before expiration date.
- [x] service account used for rotation needs to be rotated as well

**Attachments**

**Comment by Halamix2** [comment]
We're unable to automatically rotate Gardener kubeconfigs, as there is no API for that
