### ISSUE TITLE
[DRAFT] Kubernetes upgrade process

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5782]
**Description**
Goal is to support Kyma with Kubernetes version `1.xx`. Most of our pipelines have to be updated to use the next upcoming Kubernetes version.

**Tasks**
- [ ] @zhoujing2022 
    - [ ] Pre-notification for customers via [What's New]().
        This step must be done 4 weeks before Golive to PRD (Upgrade-Date on PRD: xxxxx )
- [ ] @kyma-project/jellyfish 
     - [ ] Verify k8s `1.xx` support on k3d - see [example PR](https://github.com/kyma-project/cli/pull/1306/files)
    - [ ]  Ensure no deprecated resources exist which will be no longer support on the new K8s cluster. See
       - https://github.com/kyma-project/test-infra/issues/6109
       - https://github.com/kyma-project/test-infra/issues/6519
     - [ ] Default version for Kyma CLI is k8s `1.xx` -  see [example PR](https://github.com/kyma-project/cli/pull/1306/files)
     - [ ] `kyma-upgrade-gardener-kyma2-minor-versions` job should be still using old k8s version.
- [ ] @TW
    - [ ]  document new version and add release notes (see [example PR](https://github.com/kyma-project/kyma/pull/13417))
    - [ ]  add release notes 
- [ ] @neighbors 
     - [ ] Prow jobs are updated to us k8s `1.xx` - see [example PR](https://github.com/kyma-project/test-infra/pull/5733)
         - [ ] Already existing release jobs (from last release) should be still using old k8s version.
         - [ ] kyma-upgrade-gardener-kyma2-minor-versions job should be still using old k8s version
     - [ ] Default version for kubectl is `1.xx` (Docu, Prow)
     - [ ] Setup preview job that will verify if kyma can run with k8s`1.xx` (**next** k8s version  -  see [example PR](https://github.com/kyma-project/test-infra/pull/5685))
         - [ ] create tickets (and link them) for other teams if the pipeline gets red

Previous upgrade: https://github.com/kyma-project/kyma/issues/14760

Depends on https://github.com/kyma-project/test-infra/issues/6109

**Comment by kasiakepka** [comment]
Above issues description can be used as an issue template for the next Kubernetes upgrade. However there are couple things that should be taken care of in the future:
- Automatically detect new K8s version and setup "preview" job to test it. 
- Automatically create issue in Kyma repository to report compatibility issues.

**Additional note:** Neighbors team is responsible only for maintaining and delivering the tooling.
Kyma teams are owning this process, so handling any incompatibility issues should be done by them.
I remember that there was a need to create Kyma compatibility matrix, @a-thaler can you please drive this topic?

**Comment by dekiel** [comment]
About an issue template proposal.
- Neighbours team will not update all prowjobs to run on required k8s versions. It's up to the test owner to keep it up to date.
  > @neighbors Prow jobs are based on k8s 1.xx
- Neighbours team is not an owner of this test. This task should be assigned to the team who owns that test.
  > @neighbors kyma-upgrade-gardener-kyma2-minor-versions job should be still using old k8s version.
- What does it mean exactly? There is no default kubectl version settings in Prow. We can update images maintained by Neighbours. I'm not aware of any documentation which refers to the default kubectl. Could you please provide link to docs.
  >  @neighbors [Default version for kubectl is 1.xx (Docu, Prow)
- Neighbours doesn't write and maintain tests for Kyma. This should be assigned to other team.
  > @neighbors Setup preview job that will verify if kyma can run with k8s1.xx (next k8s version)

**Comment by zhoujing2022** [comment]
@tobiscr I created an issue template under backlog: "k8s-upgrade.md".  Maybe we can close this issue already.

**Comment by tobiscr** [comment]
THX for the hint.. will close this one ;)
