### ISSUE TITLE
Prepare infrastructure and implement `gcbuild` for test-infra repository

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5835]
**Tasks**
* Prepare global config.yaml with static configuration of gcbuild, populate it on Prow, and add it to config-updater.
* Replace `build-generic.sh` based ProwJobs with new that use gcbuild for images in test-infra repository.
* Add presubmit ProwJob that runs `gcbuild-lint` on changes in the PR.
* Provide documentation about how to integrate gcbuild in the workflow
* Provide automated tests for prowjob definitions to prevent leaking credentials and enforce required configuration.

**Acceptance Criteria**
- [ ] All images in test-infra repository are build using gcbuild tool.
- [ ] All images in test-infra repository are build without using privileged containers.
- [ ] Changes in prowjobs building images in test-infra repository are covered by automated tests.
     - prevent mounting SA secret outside gcbuild prowjobs
     - prevent using non central configuration provided by neighbours team
     - prevent missconfiguration in prowjobs running gcbuild

/kind prow
/kind cleanup

estimation: 5

Parent: Create tool that run docker builds on Google Cloud Build #5637

**Comment by dekiel** [comment]
@Ressetkk should this issue be closed? At present we are not going to implement gcbuild tool.

**Comment by Ressetkk** [comment]
kaniko-build got used instead

/close
