### ISSUE TITLE
Build kubectl from sources

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5890]
Current kubectl version is build on golang 1.18.3. This is the highest version of kubectl while golang vulnerabilities are fixed in 1.18.4. We can't even use kubectl version which was build on golang 1.18.3 because we use to old k8s version. Officially kubectl support one version k8s back. In our case it would be two versions back. For now only available solution is to build kubectl in version 1.23 using golang in version minimum 1.18.4.

**Tasks**
- [ ] Build kubectl from sources manually.
- [ ] Add building of kubectl from sources to prowjob builiding k8s-tools image.

**Acceptance Criteria**
- [ ] k8s-tools use kubectl without active vulnerabilities.
- [ ] k8s-tools use kubectl in version compatible with used k8s version.

**Comment by kasiakepka** [comment]
Kubectl was already bumped https://github.com/kyma-project/third-party-images/pull/256
