### ISSUE TITLE
Prepare infrastructure and implement image-builder for kyma-project and kyma-incubator projects.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5891]
**Tasks**
- [x] Prepare global config.yaml with static configuration of gcbuild, populate it on Prow, and add it to config-updater.
- [ ] Replace `build-generic.sh` based ProwJobs with new that use image-builder.
- [x] Provide documentation about how to integrate image-builder in the workflow

**Acceptance Criteria**
- [ ] All images in test-infra repository are build using image-builder tool.
- [ ] All images in test-infra repository are build without using privileged containers.

/kind prow
/kind cleanup

**Comment by dekiel** [comment]
At present we work on using kaniko instead gcbuild as a container image building tool.

**Comment by Ressetkk** [comment]
Hijacking this issue. We have migrated some repositories:
* kyma https://github.com/kyma-project/test-infra/pull/6065
* test-infra https://github.com/kyma-project/test-infra/pull/5961
* api-gateway https://github.com/kyma-project/test-infra/pull/6117
* control-plane https://github.com/kyma-project/test-infra/pull/6110
* keda-manager https://github.com/kyma-project/test-infra/pull/6036
* lifecycle-manager https://github.com/kyma-project/test-infra/pull/6063
* runtime-watcher https://github.com/kyma-project/test-infra/pull/6073
* module-manager https://github.com/kyma-project/test-infra/pull/6073

Migrations in progress:
* kyma-incubator/compass https://github.com/kyma-project/test-infra/pull/6136
* kyma-incubator/ord-service https://github.com/kyma-project/test-infra/pull/6136
* kyma-incubator/compass-console https://github.com/kyma-project/test-infra/pull/6136


TODO:
* hydroform
* * busola - @kyma-project/hasselhoff have acknowledged this topic and will work on that
* examples - some directories have not been maintained for years. Since those are examples and are not really mission critical, we have to ask owners of those directories if maintaining jobs for them is mandatory. If not, then we should remove the jobs
* third-party-images - version are defined inside Makefile. Since image-builder invalidates usage of makefiles those variables have to be provided either inside of Dockerfile with optional parametrization, or https://github.com/kyma-project/test-infra/issues/5975 needs to be addressed
* all incubator jobs - we have to ask owners of specific repos about maintaining build pipelines there. If it's not needed then we should remove them

**Comment by tobiscr** [comment]
Blocked by https://github.com/kyma-project/test-infra/issues/6252

**Comment by kasiakepka** [comment]
Blocked by internal issue: https://github.tools.sap/kyma/test-infra/pull/153

**Comment by tobiscr** [comment]
Will be followed up in https://github.tools.sap/kyma/test-infra/issues/173
