### ISSUE TITLE
Create POC using tekton-pipeline as prowjob agent [part 1].

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6134]
**Description**

There is more and more demand for workflow like prowjobs. We see such requirements coming from developers and from kyma modularisation project. Prow has support for using a tekton pipeline as agent executing prowjob logic. However this feature is not documented. We need to research how difficult would be to setup tekton based prowjobs.

Tekton itself is a native k8s CI/CD tool. It has nice feature of Tasks catalog which stores Tasks definitions and makes easier reusing Tasks in multiple Pipelines.

**Evaluation items**
How Prow present results of tekton prowjobs?
How developers can access logs from execution?

**Tasks**
- [x] Create test k8s cluster in dev project and connect Prow to it.
- [x] Install Tekton pipelines on test k8s cluster.
- [x] Evaluate the solution is covered in https://github.com/kyma-project/test-infra/issues/6346

**Acceptance Criteria**

- Presubmit building image with image-builder, running unit tests, integration tests and linting.
- Postsubmit identifing latest build image, calling signing service and security scans.

Some resources:

Tekton documentation: https://tekton.dev/docs/getting-started/
Pipeline spec in prowjob: https://github.com/kubernetes/test-infra/blob/dfea60a61ae5d8b633d2ccf1f9b49dd87c48de16/prow/apis/prowjobs/v1/types.go#L194
Discussion about tekton agent and related documentation: https://github.com/kubernetes/test-infra/issues/13874
Documentation proposal: https://github.com/kubernetes/test-infra/pull/13974/files

**Comment by Ressetkk** [comment]
Keep in mind that Prow uses old `v1alpha1` Tekton API which is deprecated by Tekton. There is PR for quite some time https://github.com/kubernetes/test-infra/pull/27034 that updates Tekton API to `v1beta1`. We can either make POC for v1alpha1 and wait for new API support.

**Comment by Halamix2** [comment]
Tekton 0.37.2 is the latest version that supports `v1alpha1` API.

**Comment by dekiel** [comment]
Tekton hub own instance installation: https://github.com/tektoncd/hub/blob/main/docs/DEPLOYMENT.md
