### ISSUE TITLE
Remove protecode guard prowjobs.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6138]
**Description**

Protecode guard prowjobs were made recently optional. We decide to remove this jobs completely as they report the same vulnerabilities as hourly scans. Executing scans and blocking PR merge will bring value if only vulnerabilities introduced by change in PR will be reported.

**Tasks**
- [x] Remove protecode guard jobs running on pull reuqests.
- [x] Disable and archive jenkins jobs which constantly query pubsub topic.
- [x] Disable pubsub notification for image push event on gcr.
- [x] Disable and archive jenkins jobs updating data in firebase db.
- [x] Remove firebase db.
- [x] Remove pubsub topic.
- [x] Update documentation of protescan tool to mark it's not used anymore.

**Comment by Halamix2** [comment]
- [ ] remove Cloud Scheduler cron job
- [ ] remove cloud functions
