### ISSUE TITLE
[Kyma module release pipeline] Automated Kyma module release process (technical validation of Kyma modules)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6139]
**Description**

With Kyma modularisation, the approach for releasing Kyma will change from a monolithically process (all Kyma component were released together) towards microdeliveries (each component will be released individually). Kyma components will in the future be bundled in so called Kyma module. A Kyma module can include several Kyma components. The release cycle for a Kyma module will be defined and managed by the owning Kyma team.

Kyma teams will follow the SAP Microdeliveries approach (a methodology of the SAP product lifecycle management) when they are going to ship a new feature within a Kyma module. SAP Microdeliveries define a set of quality gates and are ensuring that SAP product standards get followed.

A manual verification of these quality gates is possible but time consuming and failure prone. An automated solution has to be analysed, specified and implemented.

In the first phase, we focus on automating the build, signing, publishing images and validation steps. In a second phase we focus on automating the shipment related steps (e.g. create/process a microdelivery issue, publish release notes, trigger rollout to productive systems).

**Reasons**

Automating the release and delivery process by following SLC-29 compliancy and checking product standards in an automated way will safe the release and delivery efforts for our teams. It will also reduce release cycle roundtrip times and enable a continue delivery approach for Kyma modules.

**Acceptance Criteria**
- [x] Define and visualise the high level process for an SAP product standard compliant (SLC-2x) build and release process for Kyma modules. 
    - [x] The process is aligend with release manager and non-functional requirements collected
    - [x] The process is aligned with lead architect  and non-functional requirements collected
    - [x] Technical feasibility verified
    - [x] Share final process diagram with Neigbors and Pandas team
- [x] POC: Evaluate SLC-29 compliant build and release pipeline for Kyma modules
    - [x] #6222
    - [x] POC using Prow + Tekton (#6134)
    - [x] #6223
    - [x] #6224
- [x] Ramp up team knowhow in decided CI/CD system (#6798)
- [x] #6519
    - [x] #6688
    - [x] Relevant Governance checks has to be fulfilled (#[15436](https://github.com/kyma-project/kyma/issues/15436)) 
    - [x] Automated process is aligned with Test Strategy ([#15442](https://github.com/kyma-project/kyma/issues/15442))
    - [x]  Process should finish only if every check passed successfully, otherwise a clear message has to be returned to the invoker

**Attachments**

* [SAP Wiki with process draft](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+Strategy)
* [Testing strategy issue](https://github.tools.sap/pandas/backlog/issues/1)
* [Panda EPIC for Microdelivery](https://github.tools.sap/pandas/backlog/issues/2)

**Comment by arturskorupa** [comment]
Updated with requirements for governance, testting and the process itself (inform user about  failed executions, allow gropu more PRs in a single delivery)

**Comment by tobiscr** [comment]
Relates to https://github.tools.sap/kyma/backlog/issues/3020
