### ISSUE TITLE
Create POC using tekton-pipeline: evaluation matrix [part 2]

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#6346]
**Description**

There is more and more demand for workflow like prowjobs. We see such requirements coming from developers and from kyma modularisation project. Prow has support for using a tekton pipeline as agent executing prowjob logic. However this feature is not documented. We need to research how difficult would be to setup tekton based prowjobs.

Tekton itself is a native k8s CI/CD tool. It has nice feature of Tasks catalog which stores Tasks definitions and makes easier reusing Tasks in multiple Pipelines.

**Evaluation items**
How Prow present results of tekton prowjobs?
How developers can access logs from execution?

**Tasks**
- [x] Evaluate Tekton based on the evaluation guideline (see #6222 )
    - [x] Create test pipeline using tekton-pipelines agent 
    - [x] Fill out evaluation matrix

**Acceptance Criteria**

- Presubmit building image with image-builder, running unit tests, integration tests and linting.
- Postsubmit identifing latest build image, calling signing service and security scans.

Some resources:

Tekton documentation: https://tekton.dev/docs/getting-started/
Pipeline spec in prowjob: https://github.com/kubernetes/test-infra/blob/dfea60a61ae5d8b633d2ccf1f9b49dd87c48de16/prow/apis/prowjobs/v1/types.go#L194
Discussion about tekton agent and related documentation: https://github.com/kubernetes/test-infra/issues/13874
Documentation proposal: https://github.com/kubernetes/test-infra/pull/13974/files
