### ISSUE TITLE
[CI] Setup / install Tekton instance (separate cluster) and integrate it with on our productive Prow instance(s)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6584]
**Description**

As Tekton+Prow becomes the future CI/CD solution in Kyma, we have to install a Tekton cluster and integrate it with the current Prow instance.

**This is a sub-EPIC** of [Setup CI/CD pipeline for automated Kyma module release process](https://github.com/kyma-project/test-infra/issues/6519)

AC:

- [x] #6620
- [x] #6621
- [x] #6622
- [ ] Optional: install Tekton Hub + Catalog
- [ ] Infrastructure as a code setup (see #7361 )
- [ ] Add Tekton images to security scanners (see #7361 )
- [ ] Documentation of the setup (short and crispy) (see #7361 )

**Comment by dekiel** [comment]
Don't know why I was assigned to this issue. Removing myself.
