### ISSUE TITLE
[CI] Improve Prow usability for developers via self-service portal

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6629]
**Description**

Usage of Prow can be quite difficult and is not intuitive for developers. Especially the learning curve is challenging for beginners and Prow is in general (at least on the code-base) not very intuitive to use.

To improve the general acceptance of Prow and lower entry barriers, we want to increase the usability of Prow by introducing a visualised self-service capability.

Proposed is a simple Web-based UI which enables developers to handle selected use-cases in a convenient and easy way. First use-cases we want to cover over a self-service option is:

* Creating new jobs
* Deletion of jobs
* Request the deletion of Prow-Logs of a particular job (e.g. in case of disclosing accidentally sensitive data)

For changes that require code-changes in the `test-infra` repository (e.g. changes related to jobs), the self-service will generate the necessary code / files and offers an option for downloading them. The creation of the pull-request will still happen by the developer itself (required for traceability).

AC:
- [ ] Architectural decision about the used Web-Framework is made and align within the neighbors team
- [ ] A dedicated repository is created and is configured to grant write permissions to the neighbors team
- [ ] CI/CD pipelines are setup
    - [ ] CI quality gates are implement to ensure that code-changes trigger compilation, testing and linting of the sources
    - [ ] Produced container images are scanned by SAP security scanners
- [ ] Helm charts are defined to deploy the self-service portal with a CD-approach on the Prow K8s cluster
- [ ] Simple UI is implemented which offers a visualised view for
   - [ ] Creating a simple Prow job
   - [ ] Deleting existing Prow jobs
   - [ ] Request deletion of Prow-Logs for a particular job (e.g. by proving job-id)
- [ ] For self-services features which require code-changes (e..g creating or deleting a job), the UI will generate the required files (e.g. as ZIP file) so that developers can open the related PRs by their own
- [ ] For services which require changes related to the Prow-system (e.g. deleting logs) requires an authentication by the  user. Only users within the Kyma organization are allowed to trigger such actions.

**Comment by dekiel** [comment]
> For self-services features which require code-changes (e..g creating or deleting a job), the UI will generate the required files (e.g. as ZIP file) so that developers can open the related PRs by their own
I wonder if we could use a Github oauth app and create PR as a authenticated user directly without need to provide user with zip file.

**Comment by dekiel** [comment]
> Simple UI is implemented which offers a visualised view for

The UI could have ability to present an inventory of prowjobs, presets, configsets and secrets available on a clusters.
A simple changes on prowjobs like make a prowjob optional or required.

**Comment by tobiscr** [comment]
@Ressetkk had a good idea: let's prepare a questionnaire and ask the teams where they see difficulties in Prow - compare to Github-Actions. Maybe this brings further insights on which areas we should focus on.

**Comment by tobiscr** [comment]
Basic Prow-job skeleton: https://github.com/kyma-project/test-infra/blob/main/prow/jobs/test-infra/test-infra-trusted-jobs.yaml

**Comment by tobiscr** [comment]
Obsolete as we are moving towards a service provider role.
