### ISSUE TITLE
Upgrade our pipelines to use Kubernetes version 1.25

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6740]
**Description**
We are going to upgrade Kyma to support K8s version 1.25. This requires an updated of all existing pipelines and preview-jobs to use 1.25 (respectively 1.26 for preview jobs).

**Tasks**
- [x] Prow jobs are based on k8s `1.25` - see [example PR](https://github.com/kyma-project/test-infra/pull/5733/files)
    - [x] `kyma-upgrade-gardener-kyma2-minor-versions` job should be still using the currently used k8s version and not be updated
    - [x] Existing release jobs should also not be updated to use the new K8s version
- [x] Default version for kubectl is `1.25` (Docu, Prow)
- [x] Configure preview job to verify if Kyma is compatible with k8s`1.26` (**next** k8s version  -  see [example PR](https://github.com/kyma-project/test-infra/pull/5685))
     - [x] create tickets (and link them) for other teams if the pipeline gets red (ping release-manager and provide him the issue-link)

Previous upgrade: https://github.com/kyma-project/kyma/issues/14760

Depends on https://github.com/kyma-project/test-infra/issues/6109

**Comment by tobiscr** [comment]
Requires also https://github.com/kyma-project/test-infra/pull/6761
