### ISSUE TITLE
[Daily Business] Upgrade our pipelines to use Kubernetes 1.26

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7190]
**Description**
We are going to upgrade Kyma to support K8s version 1.26. This requires an updated of all existing pipelines and preview-jobs to use 1.26 (respectively 1.27 for preview jobs).

**Tasks**
- [x] Prow jobs are based on k8s `1.26` - see [example PR](https://github.com/kyma-project/test-infra/pull/5733/files)
    - [x] `kyma-upgrade-gardener-kyma2-minor-versions` job should be still using the currently used k8s version and not be updated
    - [x] Existing release jobs should also not be updated to use the new K8s version
- [x] Default version for kubectl is `1.26` (Docu, Prow)
- [x] Configure preview job to verify if Kyma is compatible with k8s`1.27` (**next** k8s version  -  see [example PR](https://github.com/kyma-project/test-infra/pull/5685))
     - [x] create tickets (and link them) for other teams if the pipeline gets red (ping release-manager and provide him the issue-link)

Previous upgrade: https://github.com/kyma-project/test-infra/issues/6740 

Relates to https://github.com/kyma-project/kyma/issues/17018

**Comment by Sawthis** [comment]
We have [issue](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler/1640141784287809536) with Gardener clusters. Gardener has K8s 1.26.1 in preview mode(it can be the reason).
`Error from server (NotFound): secrets "rec-main-mo.kubeconfig" not found`.

I will revert K8s to 1.25 version for Gardener clusters.

**Comment by Sawthis** [comment]
Blocker in the Kyma CLI: https://github.com/kyma-project/cli/issues/1609

**Comment by Sawthis** [comment]
We had to revert k8s to 1.25 version for GCP clusters: https://github.com/kyma-project/test-infra/pull/7463 . 

```
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.26" found.
2023-04-11 11:48:49 UTC [ERROR] PID:13 --- [/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/kyma-gke-release-candidate.sh] cleanupOnError:1 AN ERROR OCCURED! Take a look at preceding log entries.
Encountered an error
     at cleanupOnError (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/kyma-gke-release-candidate.sh:74)
     at gcp::provision_k8s_cluster (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gcp.sh:1)
     at main (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/kyma-gke-release-candidate.sh:232)
```

**Comment by Sawthis** [comment]
Last known blocker: https://github.tools.sap/kyma/backlog/issues/3114

**Comment by Sawthis** [comment]
https://github.com/kyma-project/kyma/blob/main/docs/04-operation-guides/operations/02-install-kyma.md?plain=1#L13
