### ISSUE TITLE
[Operation] Centralised logging for all CI/CD components

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7239]
**Description**

Currently, each service or product of our CI/CD solution is logging decoupled form each other in different formats and even different locations.

For harmonising our log setup, we want to collect all log output in a standardised format and make them searchable in a centralised Cloud logging offering.

AC:
- [ ] Agree on the used cloud logging solution (Google Cloud operations -> GCP Cloud logging, others)
- [ ] Define standardised logging format
- [ ] Configure log shipment to GCP cloud logging for each service/product neighbors are offering

**Comment by Ressetkk** [comment]
As long as the workload runs on GCP instance, the logs can be (or even are) automatically aggregated to GCP Stackdriver.
