### ISSUE TITLE
[Daily Business] Upgrade our pipelines to use Kubernetes 1.27

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#9185]
**Description**
We are going to upgrade Kyma to support K8s version 1.27. This requires an updated of all existing pipelines and preview-jobs to use 1.27 (respectively 1.28 for preview jobs).

**Tasks**
- [ ] Prow jobs are based on k8s `1.27` - see [example PR](https://github.com/kyma-project/test-infra/pull/5733/files)
    - [ ] `kyma-upgrade-gardener-kyma2-minor-versions` job should be still using the currently used k8s version and not be updated
    - [ ] Existing release jobs should also not be updated to use the new K8s version
- [ ] Default version for kubectl is `1.27` (Docu, Prow)
- [ ] Configure preview job to verify if Kyma is compatible with k8s`1.28` (**next** k8s version  -  see [example PR](https://github.com/kyma-project/test-infra/pull/5685))
     - [ ] create tickets (and link them) for other teams if the pipeline gets red (ping release-manager and provide him the issue-link)

Previous upgrade: https://github.com/kyma-project/test-infra/issues/7190

Relates to https://github.com/kyma-project/kyma/issues/18352
