### ISSUE TITLE
Integrate Multicloud Cloud Account compliance findings into Security Dashboard

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/test-infra#9446]
**Description**

The findings from the Multicloud Security team regarding the cloud accounts used by Kyma have to be integrated into our Vulnerability Management solution including the Security Dashboard to allow developers and SREs to work on them as they do right now with vulnerabilities.

**Reasons**

SAP Global Security defines the security settings of cloud accounts used by LoBs at SAP ([Security Policy Framework](https://go.sap.corp/security-policy)) and the Multicloud has implemented a solution (Orca) to check compliance with this rules. Noncompliance is reported on a regular basis and there is also an API available to request this information on demand. Each LoB has to fix noncompliance or request an exception with a defined SLA. This process is part of a Compliance Control and regularly audited by external parties.  

**Acceptance Criteria**

- [ ] Developers and SREs are able to see open findings on the Security Dashboard
- [ ] Noncompliance findings are de-duplicated in order to allow efficient processing by developers/SREs 
- [ ] Github issues are created relating to the de-duplicated findings list and assigned to the responsible owner of the account
- [ ] Exceptions have to be taken into account before issues are created
- [ ] Developers / SREs have to be able to request exceptions for a finding (there is no consistent exception process in place and therefor "real" exceptions have to be requested by the Security Experts)

**Attachments**
