### ISSUE TITLE
Migrate linters to Github actions

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9763]
**Description**

Migrate below Prow jobs to Github actions and delete them.
  - [ ] pre-test-infra-presubmit-scanner
      - runs gitleaks scanner on pull request on test-infra repository, should be migrated,
  - [ ] pre-test-infra-validate-scripts
      - runs shellcheck on scripts in test-infra, should be migrated,
  - [ ] pre-test-infra-validate-dockerfiles
      - runs hadolint linter on pull request on test-infra, should be migrated,
  - [ ] pull-unit-test-go
      - running golang unit tests on pull requests, should be migrated,
  - [ ] pre-main-test-infra-lint
      - running linters for test-infra repository on pull requests, should be migrated,
  - [ ] pre-kyma-presubmit-scanner
      - runs gitleaks scanner on pull request on test-infra repository, is this still our responsibility?

**Reasons**

**Acceptance Criteria**

- [ ] All Prow jobs mentioned in this issue are migrated to Github actions.
- [ ] All Prow jobs mentioned in this issue are removed.

**Attachments**

https://github.com/kyma-project/test-infra/issues/9470
