### ISSUE TITLE
Remove gardener maintenance Prow jobs

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9764]
**Description**

Remove below Prow jobs after all teams Gardener tests will be migrated to Github actions.
  - [x] rotate-gardener-secrets-service-account Cloud Run is not covered by IAC - should we cover it or delete it together with below jobs?
  - [x] kyma-gardener-cleanup
      - Periodic cleanup of Gardener clusters, is this still our responsibility?
  - [x] secrets-rotate-gardener-neighbors
      - rotates credentials on neighbors gardener project, do we need this project?
  - [x] unstale-gardener-project
      - periodic creates and deletes a cluster on gardener project to prevent marking it as stale, , is this still our responsibility?
  - [x] secrets-rotate-gardener-prow
      - rotates credentials on prow gardener project, is this still our responsibility?
  - [x] secrets-rotate-gardener-kyma-dev(?)
      - rotates credentials on kyma-dev gardener project, is this still our responsibility?

**Reasons**

**Acceptance Criteria**

- [x] All Prow jobs mentioned in this issue are removed.
- [x] Delete code from test-infra repository connected with Gardener tests e.g. https://github.com/kyma-project/test-infra/tree/main/prow/scripts/lib/gardener . https://github.com/kyma-project/test-infra/issues/9764

**Attachments**

https://github.com/kyma-project/test-infra/issues/9470
