### ISSUE TITLE
Migrate GCP resources cleaners to Github actions

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9765]
**Description**

Migrate below Prow jobs to Github actions and delete them.
  - [x] orphaned-assetstore-gcp-bucket-cleaner
      - Periodic cleanup of orphaned Google cloud assetstore buckets, is this still our responsibility? What and who stores some assets in the buckets?
  - [x] ci-gcr-cleaner-untagged
      - cleans development oci registry, should be migrated,
  - [x] ci-gcr-cleaner-cache
      - cleans development oci registry, should be migrated,
  - [x] ci-gcr-cleaner-pr
      - cleans development oci registry, should be migrated,

**Reasons**

**Acceptance Criteria**

- [x] All Prow jobs mentioned in this issue are migrated to Github actions.
- [x] All Prow jobs mentioned in this issue are removed.

**Attachments**

https://github.com/kyma-project/test-infra/issues/9470

**Comment by dekiel** [comment]
The artifact registries which we use have a feature of setting cleanup policies. If we can achieve our cleanup goals by setting a registry cleanup policy we should do it that way, instead running a workflow with a tool calling API. The policy must be set with IaC.

We should not take a reponsibility for cleanup of any buckets which do not store our data. If the teams have any buckets in our project, we should give them a permissions to manage their buckets and leave this task to them.
