### ISSUE TITLE
Remove not needed anymore sap-kyma-workloads GCP project and cleaner Prow jobs

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9771]
**Description**

On 18 of October we can remove access to the sap-kyma-workloads GCP project and remove below jobs.
On 31 of October we can delete the sap-kyma-workloads GCP project.

 Won't be needed after migration outside of Prow.
  - [x] gcloud-ssh-keys-cleaner
    - cleans os-login ssh keys on gcp project, not needed after prow and workloads project deletion
   - [x] orphaned-disks-cleaner
      - cleans orphaned disks on gcp project, not needed after prow and workloads project deletion
  - [x] orphaned-ips-cleaner
      - cleans orphaned ips on gcp project, not needed after prow and workloads project deletion
  - [x] orphaned-clusters-cleaner
      - cleans orphaned clusters on gcp project, not needed after prow and workloads project deletion
  - [x] orphaned-vms-cleaner
      - cleans orphaned vms on gcp project, not needed after prow and workloads project deletion
  - [x] orphaned-loadbalancer-cleaner
      - cleans orphaned lbs on gcp project, not needed after prow and workloads project deletion
  - [x] orphaned-dns-cleaner
      - cleans orphaned dns on gcp project, probably not needed after prow and workloads project deletion

**Reasons**

**Acceptance Criteria**

- [x] All Prow jobs mentioned in this issue are removed.
- [ ] sap-kyma-workloads GCP project is removed.

**Attachments**

https://github.com/kyma-project/test-infra/issues/9470

**Comment by Sawthis** [comment]
sap-kyma-prow-workloads is in DELETION_REQUESTED status.

**Comment by Sawthis** [comment]
https://github.tools.sap/eng/repose/blob/master/doc/internal/runbooks/accounts/l1-delete-account.md
