### ISSUE TITLE
[Daily Business] Upgrade our pipelines to use Kubernetes 1.28

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/test-infra#9807]
**Description**
We are going to upgrade Kyma to support K8s version 1.28. This requires an updated of all existing pipelines and preview-jobs to use 1.28 (respectively 1.29 for preview jobs). (Please complete this task before 14.Feb.2024)

**Tasks**
- [x] Prow jobs are based on k8s `1.28` - see [example PR](https://github.com/kyma-project/test-infra/pull/5733/files)
    - [x] `kyma-upgrade-gardener-kyma2-minor-versions` job should be still using the currently used k8s version and not be updated
    - [x] Existing release jobs should also not be updated to use the new K8s version
- [x] Default version for kubectl is `1.28` (Docu, Prow)
- [x] Configure preview job to verify if Kyma is compatible with k8s`1.29` (**next** k8s version  -  see [example PR](https://github.com/kyma-project/test-infra/pull/5685))
     - [x] create tickets (and link them) for other teams if the pipeline gets red (ping release-manager and provide him the issue-link)

Previous upgrade: https://github.com/kyma-project/test-infra/issues/9185

Relates to https://github.com/kyma-project/kyma/issues/18558
